### ISSUE TITLE
error while using the model with CTC wordbeamsearch

### ISSUE THREAD

**Issue by NitiKaur** [lamhoangtung/LineHTR#8]
tensorflow version 1.8
python version 3.7
ubuntu 18.04 LTS

I get the following error after copying the tfwordbeamsearch.so file of the CTC repository into the src directory of your repository.
Traceback (most recent call last):
File "main.py", line 194, in
main()
File "main.py", line 178, in main
decoderType, mustRestore=False)
File "/home/niti/Desktop/HTR/HTR/src/Model.py", line 36, in init
self.setupCTC()
File "/home/niti/Desktop/HTR/HTR/src/Model.py", line 177, in setupCTC
chars = codecs.open(FilePaths.wordCharList.txt, 'r').read()
AttributeError: type object 'FilePaths' has no attribute 'wordCharList'

Also is there any way I can recognise the characters like ./,!=+- etc instead of the word characters only using CTC?
Also, can this be trained on Google colab

**Comment by NitiKaur** [comment]
tensorflow version 1.8
python version 3.7
ubuntu 18.04 LTS

I get the following error after copying the tfwordbeamsearch.so file of the CTC repository into the src directory of your repository.
Traceback (most recent call last):
  File "main.py", line 194, in <module>
    main()
  File "main.py", line 178, in main
    decoderType, mustRestore=False)
  File "/home/niti/Desktop/HTR/HTR/src/Model.py", line 36, in __init__
    self.setupCTC()
  File "/home/niti/Desktop/HTR/HTR/src/Model.py", line 177, in setupCTC
    chars = codecs.open(FilePaths.wordCharList.txt, 'r').read()
AttributeError: type object 'FilePaths' has no attribute 'wordCharList'

Also is there any way I can recognise the characters like ./,!=+- etc instead of the word characters only using CTC?
Also, can this be trained on Google colab

**Comment by lamhoangtung** [comment]
Seems like the code that you having issue with was not belong to this repo but https://github.com/githubharald/SimpleHTR
